#!/bin/bash

ccc=/home/vivien/c-chess-cli/c-chess-cli

$ccc -each tc=5+0.1 \
	-engine "cmd=/home/vivien/Minic/Tourney/minic_dev_linux_x64" option.Threads=1 name="Minic 1threads" \
	-engine "cmd=/home/vivien/Minic/Tourney/minic_dev_linux_x64" option.Threads=2 name="Minic 2threads" \
	-engine "cmd=/home/vivien/Minic/Tourney/minic_dev_linux_x64" option.Threads=4 name="Minic 4threads" \
	-engine "cmd=/home/vivien/Minic/Tourney/minic_dev_linux_x64" option.Threads=8 name="Minic 8threads" \
	-engine "cmd=/home/vivien/Minic/runmpi.sh 2" \
	-engine "cmd=/home/vivien/Minic/runmpi.sh 4" \
	-engine "cmd=/home/vivien/Minic/runmpi.sh 8" \
	-engine "cmd=/home/vivien/Minic/runmpi.sh 16" \
	-games 4 -rounds 100 -concurrency 1 -pgn out.pgn \
	-openings file=/home/vivien/Minic/Book_and_Test/OpeningBook/Pohl_AntiDraw_Openings_V1.5/Unbalanced_Human_Openings_V3/UHO_V3_+150_+159/UHO_V3_8mvs_big_+140_+169.epd order=random &
