#!/bin/bash

dir=$(readlink -f $(dirname $0)/../../)

CUTECHESS=cutechess-cli
engines=""

engines="$engines -engine conf=minic_dev"
#engines="$engines -engine conf=minic_devl0"
engines="$engines -engine conf=minic_devl1"
engines="$engines -engine conf=minic_devl10"
engines="$engines -engine conf=minic_devl20"
engines="$engines -engine conf=minic_devl30"
engines="$engines -engine conf=minic_devl40"
engines="$engines -engine conf=minic_devl50"
engines="$engines -engine conf=minic_devl60"
engines="$engines -engine conf=minic_devl70"
engines="$engines -engine conf=minic_devl80"
engines="$engines -engine conf=minic_devl90"
engines="$engines -engine conf=minic_devl100"

echo $engines

$CUTECHESS $engines -each proto=xboard tc=40/10 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/2moves_LT_1000.pgn format=pgn order=random plies=24 -recover -concurrency 7 -tournament gauntlet > tournament_level.log 2>&1 &


