#!/bin/bash

dir=$(readlink -f $(dirname $0)/../../)

CUTECHESS=cutechess-cli
engines="-engine conf=minic_3.03_niggling_nymph"
engines="$engines -engine conf=minic_3.03"
engines="$engines -engine conf=minic_dev_test_nnue_pytorch"

echo $engines

$CUTECHESS $engines -each proto=uci tc=3+0.1 timemargin=50 -rounds 10000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=/ssd/Minic/Book_and_Test/OpeningBook/Hert500.pgn format=pgn order=random plies=24 -recover -concurrency 7 > tournament_nnue_torch.log 2>&1 &


