#!/bin/bash

dir=$(readlink -f $(dirname $0)/../../)

/usr/games/xboard -fcp "$dir/Dist/Minic3/minic_dev_linux_x64 -xboard -debugMode 1" -fd "$dir/Dist/" -scp "$dir/Dist/Minic3/minic_${1}_linux_x64_skylake -xboard" -sd "$dir/Dist/" -tc 0:20 -mps 40 -ponder -debug 

