#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

cd $dir

FATHOM_PRESENT=0
if [ -e Fathom/src/tbprobe.h ]; then
   FATHOM_PRESENT=1
   echo "found Fathom lib, trying to build"
   $dir/Tools/buildFathom.sh "$@"
fi

if [ $FATHOM_PRESENT = "1" ]; then
   lib=fathom_dev_linux_x64.o
   OPT="$OPT $dir/Fathom/src/$lib -I$dir/Fathom/src"
fi

g++ -g -O3 -DNDEBUG -ggdb -flto --std=c++14 Source/*.cpp -ISource $OPT -lpthread -DDEBUG_TOOL -o minic.perf
#perf record -g ./minic.perf -analyze "r1bqkb1r/pp3ppp/1np1pn2/6N1/2BP4/8/PPP1QPPP/R1B1K1NR w KQkq - 1 1" 15 -book 0
perf record -g ./minic.perf -perft "start" 6 -quiet 0
perf report
