#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

cd $dir

g++ -g -O2 -ggdb -flto --std=c++14 minic.cc -lpthread -DDEBUG_TOOL -o minic.perf
perf record -g ./minic.perf -analyze "r1bqkb1r/pp3ppp/1np1pn2/6N1/2BP4/8/PPP1QPPP/R1B1K1NR w KQkq - 1 1" 15 -book 0
perf report
