#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

cd $dir

OPT="-pg -O3 -no-pie --std=c++17 -DUSE_AVX2"
export CXX=g++
export CC=gcc

FATHOM_PRESENT=0
if [ -e Fathom/src/tbprobe.h ]; then
   FATHOM_PRESENT=1
   echo "found Fathom lib, trying to build"
   $dir/Tools/buildFathom.sh "$@"
fi

if [ $FATHOM_PRESENT = "1" ]; then
   lib=fathom_dev_linux_x64.o
   OPT="$OPT $dir/Fathom/src/$lib -I$dir/Fathom/src"
fi

g++ Source/*.cpp -ISource -ISource/nnue -ISource/nnue/architectures -ISource/nnue/features -ISource/nnue/layers $OPT -lpthread -DDEBUG_TOOL -o minic.prof
./minic.prof -analyze "shirov" 25 -quiet 0
#./minic.prof -evalSpeed Book_and_Test/Tuning/lichess-new-labeled.epd
#./minic.prof -perft "start" 7 -book 0 -quiet 0
gprof minic.prof gmon.out | gprof2dot | dot -Tpng -o prof.png
gprof minic.prof gmon.out > prof.txt

