#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

cd $dir

OPT="-g -O3 -flto --std=c++14"
export CXX=g++
export CC=gcc

FATHOM_PRESENT=0
if [ -e Fathom/src/tbprobe.h ]; then
   FATHOM_PRESENT=1
   echo "found Fathom lib, trying to build"
   $dir/Tools/buildFathom.sh "$@"
fi

if [ $FATHOM_PRESENT = "1" ]; then
   lib=fathom_dev_linux_x64.o
   OPT="$OPT $dir/Fathom/src/$lib -I$dir/Fathom/src"
fi

g++ Source/*.cpp -ISource $OPT -lpthread -DDEBUG_TOOL -o minic.valgrind
#valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./minic.valgrind -analyze "shirov" 20
#valgrind --tool=exp-sgcheck ./minic.valgrind -analyze "shirov" 20
valgrind --log-file=valgrind.log --tool=memcheck --track-origins=yes ./minic.valgrind -analyze "shirov" 20 

