#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
engines=""

engines="$engines -engine conf=minic_$1 proto=xboard"
engines="$engines -engine conf=igel-$2 proto=uci"

echo $engines

$CUTECHESS $engines -each tc=40/20 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/2moves_LT_1000.pgn format=pgn order=random plies=24 -recover -concurrency 1 > tournament_igel.log 2>&1 &


