#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

/usr/games/xboard -fcp "$dir/Dist/minic_dev_linux_x64_see4.2 -xboard" -fd "$dir" -scp "/usr/games/fairymax"  -sd "/usr/games/" -tc 0:20 -mps 40 -ponder
#-debug

