#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

/usr/games/xboard -fcp "$dir/a.out" -fd "$dir" -scp "$dir/Dist/Minic2/minic_dev_linux_x64 -xboard -level $1" -sd "$dir/Dist/" -tc 0:30 -mps 40 -ponder -debug

