#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
engines=""

engines="$engines -engine conf=minic_dev"
engines="$engines -engine conf=minic_1.35"
#engines="$engines -engine conf=asymptote_v0.6"
#engines="$engines -engine conf=Fridolin310"
#engines="$engines -engine conf=GreKo"
#engines="$engines -engine conf=igel-1.9.2"
#engines="$engines -engine conf=redqueen-1.1.98"
#engines="$engines -engine conf=minic_0.47"
#engines="$engines -engine conf=minic_0.57"
#engines="$engines -engine conf=minic_0.65"
#engines="$engines -engine conf=minic_0.76"
#engines="$engines -engine conf=minic_0.80"
#engines="$engines -engine conf=minic_0.86"
engines="$engines -engine conf=Topple_master"
#engines="$engines -engine conf=Winter0.6"
engines="$engines -engine conf=Winter0.7"
#engines="$engines -engine conf=zurichess-neuchatel"
#engines="$engines -engine conf=minic_dev"
engines="$engines -engine conf=minic_1.19"
engines="$engines -engine conf=minic_1.42"
engines="$engines -engine conf=rodentIII"
engines="$engines -engine conf=komodo-13-64-ja"
engines="$engines -engine conf=amoeba"
engines="$engines -engine conf=Hakkapeliitta"
engines="$engines -engine conf=marvin_64bit_popcnt"
engines="$engines -engine conf=Counter-v3.4-linux-64"
#engines="$engines -engine conf=igel-2.1"
engines="$engines -engine conf=demolito"
engines="$engines -engine conf=igel-last"

echo $engines

$CUTECHESS $engines -each tc=40/60 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/Adam-Hair-12moves-397457.pgn format=pgn order=random plies=24 -recover -concurrency 8 -tournament gauntlet > tournament.log 2>&1 &
