#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
ARCH=_avx2_bmi2
engines=""

engines="$engines -engine name=minic_0.47 cmd=$dir/Dist/minic_0.47_linux_x64$ARCH arg=-xboard dir=$dir"
engines="$engines -engine name=minic_0.75 cmd=$dir/Dist/minic_0.65_linux_x64$ARCH arg=-xboard dir=$dir"
engines="$engines -engine name=minic_0.75 cmd=$dir/Dist/minic_0.78_linux_x64$ARCH arg=-xboard dir=$dir"

engines="$engines -engine conf=asymptote-v0.4.2"
engines="$engines -engine conf=ruy-1.1.9"
engines="$engines -engine conf=wyldchess1.51"
engines="$engines -engine conf=zurichess-neuchatel"
engines="$engines -engine conf=minic_0.47"
engines="$engines -engine conf=minic_0.57"
engines="$engines -engine conf=Fridolin310"
engines="$engines -engine conf=GreKo"
engines="$engines -engine conf=igel_1.7"
engines="$engines -engine conf=redqueen-1.1.98"
engines="$engines -engine conf=minic_0.65"
engines="$engines -engine conf=minic_0.78"
engines="$engines -engine conf=asymptote_v0.6"
engines="$engines -engine conf=Topple"
engines="$engines -engine conf=Winter"
engines="$engines -engine conf=minic_dev"

echo $engines

$CUTECHESS $engines -each proto=xboard tc=40/60 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/2moves_LT_1000.pgn format=pgn order=random plies=24 -recover -concurrency 8 > tournament.log 2>&1 &
