#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
ARCH=_avx2_bmi2
engines=""

if [ "$1" != "nodev" ]; then
   #engines="$engines -engine name=minic_dev cmd=$dir/Tourney/minic_dev_linux_x64 arg=-xboard dir=$dir"
   engines="$engines -engine name=minic_dev cmd=$dir/Dist/minic_dev_linux_x64 arg=-xboard dir=$dir"
fi

engines="$engines -engine name=minic_0.47 cmd=$dir/Dist/minic_0.47_linux_x64$ARCH arg=-xboard dir=$dir"
engines="$engines -engine name=minic_0.75 cmd=$dir/Dist/minic_0.75_linux_x64$ARCH arg=-xboard dir=$dir"

echo $engines

$CUTECHESS $engines -each proto=xboard tc=40/20 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/2moves_LT_1000.pgn format=pgn order=random plies=24 -recover -concurrency 2 > tournament.log 2>&1 &


