#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=cutechess-cli
ARCH=_avx2_bmi2
engines="-engine conf=minic_3.03_niggling_nymph"

nnuedir=$(readlink -f $1)
shift
echo "NNUE file in $nnuedir"

for i in $@ ; do
   echo $i
   engines="$engines -engine name=minic_nnue_test_$i cmd=/ssd/Minic/Dist/Minic3/minic_3.03_linux_x64_skylake dir=/ssd/Minic/Dist/Minic3/ arg=-uci arg=-NNUEFile arg=$nnuedir/epoch=$i.ckpt"
done
echo $engines

$CUTECHESS $engines -each proto=uci tc=3+0.1 timemargin=50 -rounds 10000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=/ssd/Minic/Book_and_Test/OpeningBook/Hert500.pgn format=pgn order=random plies=24 -recover -concurrency 7 > tournament_nnue.log 2>&1 &


