#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

/usr/games/xboard -fcp "$dir/a.out" -fd "$dir" -scp "/media/BK1/www/p/chessEngine/weini/other/tscp181b/tscp" -sd "/ssd/engines/tscp" -tc 0:20 -mps 40 -xponder -debug

