#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
engines=""

engines="$engines -engine conf=stockfish"
engines="$engines -engine conf=RubiChess"
engines="$engines -engine conf=komodo-10-linux"
engines="$engines -engine conf=Defenchess_2.2"

echo $engines

$CUTECHESS $engines -each tc=0/30+0.25 timemargin=200 -rounds 10000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/test.pgn format=pgn order=random plies=39 -recover -concurrency 7 > tournament_pos.log 2>&1 &


