#!/bin/bash

dir=$(readlink -f $(dirname $0)/..)

CUTECHESS=$dir/../cutechess/projects/cli/cutechess-cli
engines=""

engines="$engines -engine conf=minic_dev"
engines="$engines -engine conf=minic_1.35"
engines="$engines -engine conf=Topple_master"
engines="$engines -engine conf=Winter0.7"
#engines="$engines -engine conf=zurichess-neuchatel"
engines="$engines -engine conf=minic_1.19"
engines="$engines -engine conf=minic_1.45"
engines="$engines -engine conf=minic_1.50"
engines="$engines -engine conf=rodentIV"
engines="$engines -engine conf=komodo-13-64-ja"
engines="$engines -engine conf=amoeba"
engines="$engines -engine conf=Hakkapeliitta"
engines="$engines -engine conf=marvin_64bit_popcnt"
engines="$engines -engine conf=Counter-v3.4-linux-64"
engines="$engines -engine conf=demolito"
engines="$engines -engine conf=RubiChess"
engines="$engines -engine conf=Defenchess_2.2"
engines="$engines -engine conf=igel-last"
engines="$engines -engine conf=stockfish"

echo $engines

$CUTECHESS $engines -each tc=40/60 timemargin=200 -rounds 1000 -pgnout pgn_$(date +"%Y_%m_%d"_%H%M%S).out -ratinginterval 1 -repeat -openings file=$dir/OpeningBook/Adam-Hair-12moves-397457.pgn format=pgn order=random plies=24 -recover -concurrency 8 -tournament gauntlet > tournament.log 2>&1 &
