name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: make
      shell: bash
      env:
       CC:   gcc-10
       CXX:  g++-10
  
